services:
  db:
    image: mysql:5.7
    container_name: todo_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: todo_backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/var/www/html
      - ./backend:/000-default.conf
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: todo_frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend

volumes:
  db_data:
networks:
  symfony:
    driver: bridge
